comeco = int(input("Começo do interalo"))
fim = int(input("Fim do intervalo"))

for c in range(comeco,fim):
    print(c*0)
    print(c*1)
    print(c*2)
    print(c*3)
    print(c*4)
    print(c*5)
    print(c*6)
    print(c*7)
    print(c*8)
    print(c*9)
    print(c*10)